name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy_to_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Stop services on VM
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            source /opt/py_bot_boltun/venv/bin/activate
            sudo systemctl stop web.service app.service
          EOF

      - name: Pull updates on VM
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            cd /opt/py_bot_boltun
            source venv/bin/activate
            git pull origin master
          EOF

      - name: Start services on VM
        run: |
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            source /opt/py_bot_boltun/venv/bin/activate
            sudo systemctl start web.service app.service
          EOF
